;; [[file:hh.org::*Сущности и автоматы][entity_and_automates]]
(in-package #:moto)
(define-automat vacancy "Автомат вакансии"
  ((id serial)
   (src-id integer)
   (archive boolean)
   (name varchar)
   (currency (or db-null varchar))
   (base-salary (or db-null integer))
   (salary (or db-null integer))
   (salary-text (or db-null varchar))
   (salary-max (or db-null integer))
   (salary-min (or db-null integer))
   (emp-id (or db-null integer))
   (emp-name varchar)
   (city varchar)
   (metro varchar)
   (experience varchar)
   (date varchar)
   (respond varchar)
   (descr varchar)
   (notes (or db-null varchar))
   (response (or db-null varchar)))
  (:accept :discard :offer :interview :testjob :invite :reject :beenviewed :responded :interesting :uninteresting :unsort)
  ((:unsort :uninteresting :uns-uni)
   (:unsort :interesting :uns-int)
   (:unsort :responded :uns-res)
   (:uninteresting :interesting :uni-int)
   (:uninteresting :responded :uni-res)
   (:uninteresting :uninteresting :uni-uni)
   (:interesting :uninteresting :int-uni)
   (:interesting :responded :int-res)
   (:interesting :interesting :int-int)
   (:responded :beenviewed :res-bee)
   (:responded :uninteresting :res-uni)
   (:responded :reject :res-rej)
   (:responded :invite :res-inv)
   (:responded :responded :res-res)
   (:beenviewed :uninteresting :bee-uni)
   (:beenviewed :reject :bee-rej)
   (:beenviewed :invite :bee-inv)
   (:beenviewed :testjob :bee-tes)
   (:beenviewed :beenviewed :bee-bee)
   (:testjob :invite :tes-inv)
   (:testjob :interview :tes-int)
   (:testjob :uninteresting :tes-uni)
   (:testjob :offer :tes-off)
   (:testjob :testjob :tes-tes)
   (:reject :responded :rej-res)
   (:reject :uninteresting :rej-uni)
   (:reject :reject :rej-rej)
   (:invite :invite :inv-inv)
   (:invite :uninteresting :inv-uni)
   (:invite :testjob :inv-tes)
   (:invite :interview :inv-int)
   (:interview :uninteresting :int-uni)
   (:interview :discard :int-dis)
   (:interview :testjob :int-tes)
   (:interview :interview :int-int)
   (:discard :uninteresting :dis-uni)
   (:discard :discard :dis-dis)
   (:interview :offer :int-off)
   (:offer :uninteresting :off-uni)
   (:offer :offer :off-off)
   (:offer :accept :off-onj)
   (:accept :accept :acc-acc)))

(define-automat resume "Автомат резюме"
  ((id serial)
   (src-id (or db-null varchar))
   (res-id (or db-null varchar))
   (title varchar))
  (:accept :discard :offer :interview :testjob :invite :reject :beenviewed :responded :interesting :uninteresting :unsort)
  ((:unsort :uninteresting :uns-uni)
   (:unsort :interesting :uns-int)
   (:unsort :responded :uns-res)
   (:uninteresting :interesting :uni-int)
   (:uninteresting :responded :uni-res)
   (:uninteresting :uninteresting :uni-uni)
   (:interesting :uninteresting :int-uni)
   (:interesting :responded :int-res)
   (:interesting :interesting :int-int)
   (:responded :beenviewed :res-bee)
   (:responded :uninteresting :res-uni)
   (:responded :reject :res-rej)
   (:responded :invite :res-inv)
   (:responded :responded :res-res)
   (:beenviewed :uninteresting :bee-uni)
   (:beenviewed :reject :bee-rej)
   (:beenviewed :invite :bee-inv)
   (:beenviewed :testjob :bee-tes)
   (:beenviewed :beenviewed :bee-bee)
   (:testjob :invite :tes-inv)
   (:testjob :interview :tes-int)
   (:testjob :uninteresting :tes-uni)
   (:testjob :offer :tes-off)
   (:testjob :testjob :tes-tes)
   (:reject :responded :rej-res)
   (:reject :uninteresting :rej-uni)
   (:reject :reject :rej-rej)
   (:invite :invite :inv-inv)
   (:invite :uninteresting :inv-uni)
   (:invite :testjob :inv-tes)
   (:invite :interview :inv-int)
   (:interview :uninteresting :int-uni)
   (:interview :discard :int-dis)
   (:interview :testjob :int-tes)
   (:interview :interview :int-int)
   (:discard :uninteresting :dis-uni)
   (:discard :discard :dis-dis)
   (:interview :offer :int-off)
   (:offer :uninteresting :off-uni)
   (:offer :offer :off-off)
   (:offer :accept :off-onj)
   (:accept :accept :acc-acc)))

(define-automat rule "Автомат правила"
  ((id serial)
   (name varchar)
   (user-id integer)
   (rank integer)
   (ruletype varchar)
   (antecedent varchar)
   (consequent varchar)
   (notes (or db-null varchar)))
  (:inactive :active)
  ((:active :inactive :rule-activation)
   (:inactive :active :rule-deactivation)))

(define-automat srcaccount "Автомат аккаунта"
  ((id serial)
   (user_id integer)
   (src_source varchar)
   (src_login varchar)
   (src_password varchar)
   (src_fio varchar))
  (:wrong :logged :inactive :active)
  ((:active :inactive :account-activation)
   (:inactive :active :account-deactivation)
   (:active :logged :account-login)
   (:logged :active :account-logout)
   (:active :wrong :account-wrong)))
;; entity_and_automates ends here
