;; [[file:hh.org::*Сущности и автоматы][entity_and_automates]]
(in-package #:moto)
(define-automat vacancy "Автомат вакансии"
  ((id serial)
   (src-id integer)
   (archive boolean)
   (name varchar)
   (currency (or db-null varchar))
   (base-salary (or db-null integer))
   (salary (or db-null integer))
   (salary-text (or db-null varchar))
   (salary-max (or db-null integer))
   (salary-min (or db-null integer))
   (emp-id (or db-null integer))
   (emp-name varchar)
   (city varchar)
   (metro varchar)
   (experience varchar)
   (date varchar)
   (respond varchar)
   (descr varchar)
   (notes (or db-null varchar))
   (response (or db-null varchar)))
  (:responded :interesting :uninteresting :unsort)
  ((:unsort :uninteresting :unsort-uninteresting)
   (:unsort :interesting :unsort-interesting)
   (:unsort :responded :unsort-responded)
   (:uninteresting :interesting :uninteresting-interesting)
   (:uninteresting :responded :uninteresting-responded)
   (:uninteresting :uninteresting :uninteresting-uninteresting)
   (:interesting :uninteresting :interesting-uninteresting)
   (:interesting :responded :interesting-responded)
   (:interesting :interesting :interesting-interesting)
   (:responded :responded :responded-responded)))
;; entity_and_automates ends here
