
Этот документ отвечает на вопросы
- Что нужно сделать чтобы собрать проект
- Что нужно сделать чтобы запусить собранный проект

Можно начинать сразу со второй части, если вы не планируете
дорабатывать проект или просто хочется попробовать

* Сборка

  Создаем путь, где будет все лежать.

  mkdir ~/repo

  Скачиваем последнюю версию с https://github.com/rigidus/moto.git и
  положим ее в =~/repo/moto=. Соблюдать эти пути необязательно, но
  остальные рекомендации ниже тогда придется скорректировать.

  Открываем =~/repo/moto/doc.org= в emacs-e

  Загружаем генераторы: =M-x load-file= =~/repo/moto/generators.el=
  Без этого шага при генерации не найдуться некоторые необходимые
  функции, что вызовет ошибку генерации.

  Выполняем генерацию кода (org-babel-tangle) в открытом в emacs-е
  файле =~/repo/moto/doc.org=, нажимая комбинацию клавишь =C-c C-v t=

  Сгенерируется множество файлов проекта, в основном в каталоге
  =~/repo/moto/src=

  Выполняем генерацию документации в формате html (org-export) в
  открытом в emacs-е файле =~/repo/moto/doc.org= нажимая комбинацию
  клавишь =C-c C-e h=

  Сгенерируется файл документации =~/repo/moto/doc.html=

  Аналогичным образом можно поступать со всеми файлами модулей - это
  файлы с расширением =org=, которые лежат в корневом каталоге
  =~/repo/moto/=

  Если понадобится изменить процесс генерации - функции, которые за
  него отвечают лежат в "Определения сущностей" -> "Функции для
  кодогенерации сущностей"

* Запуск

  Чтобы запустить проект, необходимо иметь:
  - sbcl
  - quicklisp
    Необходимо, чтобы quicklisp мог найти систему проекта. Для этого
    в =~/.sbclrc= дописываем следущий код

    #+BEGIN_SRC lisp
      #+quicklisp
      (mapcar #'(lambda (x)
                  (pushnew x ql:*local-project-directories*))
             (list
                   #P"~/repo/moto/"
                   ))
    #+END_SRC

  - postgres
  Эти данные для входа лежат в ~/repo/moto/doc.org в разделе
  "Глобальные определения"
    - Пользователя postgres
    - Базу данных

  Обеспечив выполнение этих условий, заходим в =emacs=, набираем =M-x
  slime= и в открывшемся буфере =(ql:quickload "moto")=

  Все должно заработать. Если нет - связывайтесь со мной.

  Чуть не забыл, веб-интерфейс размещен на порту 9997
